nota1 = input('Digite a primeira nota:')
nota2 = input('Digite a primeira segunda:')
nota3 = input('Digite a primeira terceira:')
nota4 = input('Digite a primeira quarta:')
n1 = int(nota1)
n2 = int(nota2)
n3 = int(nota3)
n4 = int(nota4)
print('A média aritmética é', (n1 + n2 + n3 + n4)/4)
